[project]
name = "tgit"
version = "0.10.0"
description = "Tool for Git Interaction Temptation (tgit): An elegant CLI tool that simplifies and streamlines your Git workflow, making version control a breeze."
authors = [{ name = "Jannchie", email = "jannchie@gmail.com" }]
dependencies = [
    "rich>=13.9.2",
    "pyyaml>=6.0.2",
    "inquirer>=3.4.0",
    "gitpython>=3.1.43",
    "openai>=1.52.0",
]
readme = { content-type = "text/markdown", file = "README.md" }
requires-python = ">= 3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Version Control",
    "Topic :: Utilities",
    "Typing :: Typed",
]
keywords = ["git", "tool", "changelog", "version", "commit"]
license = "MIT"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = ["black>=24.10.0", "isort>=5.13.2"]

[tool.black]
line-length = 160

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["tgit"]

[project.scripts]
tgit = "tgit:cli.main"
