[project]
name = "relib"
version = "1.1.2"
requires-python = ">=3.12"
dependencies = [
  "numpy",
  "termcolor",
]
authors = [
  {name = "Hampus Hallman"}
]
# description = ""
readme = "README.md"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/Reddan/relib.git"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["relib"]
