[tool.poetry]
name = "stofory-sdk"
version = "0.1.32"
description = ""
authors = ["k <nikita.gluhovsky@gmail.com>"]
readme = "README.md"
packages = [{include = "stofory_sdk"}]

[tool.poetry.dependencies]
python = "^3.12"
advanced-alchemy = "^0.20.0"
SQLAlchemy-Utils = "^0.41.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
