[tool.poetry]
name = "mongo-analyser"
version = "0.1.5"
description = "A minimalistic tool for analysing and extracting the schema of a MongoDB collection."
authors = ["Hassan Abedi <hassan.abedi.t@gmail.com>"]
maintainers = ["Hassan Abedi <hassan.abedi.t@gmail.com>"]
license = "MIT"
readme = "README.md"
include = ["README.md", "LICENSE"]
packages = [{ include = "mongo_analyser", from = "." }]
repository = "https://github.com/habedi/mongo-analyser"
documentation = "https://github.com/habedi/mongo-analyser/blob/main/docs/index.md"
classifiers = [
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3",
]
keywords = ["mongodb", "python", "nosql", "command-line tool", "json"]

[tool.poetry.dependencies]
python = "^3.9"
pymongo = "^4.10.1"
pytz = "^2024.2"

[tool.poetry.dev-dependencies]
pytest = "^8.0.1"
pytest-cov = "^5.0.0"
pytest-mock = "^3.14.0"
mypy = "^1.11.1"
poetry-dynamic-versioning = "^1.4.0"
ruff = "^0.7.0"

[tool.poetry.scripts]
mongo_analyser = "mongo_analyser.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [".", "mongo_analyser"]

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
disallow_untyped_calls = true
strict_optional = true
warn_redundant_casts = true

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
versioning = "semver"  # Semantic Versioning

# Ruff configuration
[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv"
]
line-length = 100
indent-width = 4
src = ["mongo_analyser", "tests"]
target-version = "py311"

[tool.ruff.lint]
select = ["ANN", "D", "E", "F", "I"]
ignore = [
    "ANN101", # Don't annotate self
    "ANN102"  # Don't annotate cls
]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = []
