[tool.poetry]
name = "nonebot-plugin-ddrace"
version = "0.0.5"
description = "提供 DDNet 成绩查询功能"
authors = ["gongfuture <gongfuture@outlook.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/gongfuture/nonebot-plugin-ddrace"
repository = "https://github.com/gongfuture/nonebot-plugin-ddrace"
# documentation = "https://github.com/gongfuture/nonebot-plugin-ddrace/wiki"
keywords = ["bot", "qq", "qqbot", "onebotv11", "onebot", "nonebot2", "nonebot", "ddrace", "ddnet"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
packages = [{ include = "nonebot_plugin_ddrace"}]

[tool.poetry.dependencies]
python = ">3.9,<4.0"
nonebot2 = ">=2.3.3"
httpx = ">=0.24.1,<0.27.2"
beautifulsoup4 = "^4.12.3"
nonebot_plugin_apscheduler = ">=0.2.0"
nonebot-plugin-localstore = ">=0.7.0"
nonebot-plugin-userinfo = ">=0.2.0"
# nonebot-plugin-session = ">=0.3.0"
nonebot-plugin-send-anything-anywhere = ">=0.5,<0.8"
nonebot-plugin-htmlrender = ">=0.3.5"
pydantic = "<3.0.0"
nonebot-adapter-onebot = "^2.4.5"


[tool.poetry.urls]
"Bug Tracker" = "https://github.com/gongfuture/nonebot-plugin-ddrace/issues"


[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
