[project]
name = "APISimplify"
version = "0.0.4"
description = "A simple API toolkit for Python developers"
readme = "README.md"
requires-python = ">=3.6.0"  # This is the correct key
authors = [
    { name = "master_wasdondiscord", email = "masterioempo@gmail.com" }
]
license = { file = "LICENSE" }  # Make sure to create a LICENSE file in your repository

dependencies = [
    "requests >=2.25.0",
    "discord >=1.0.0",
    "Pillow >=8.0.0",
    "jsonschema >=3.2.0"
]

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
