[tool.poetry]
name = "spei-python"
version = "0.51.1"
description = ""
authors = ["tech <tech@fondeadora.com>"]
readme = "README.md"
packages = [{include = "spei"}]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
lxml = "^4.7.1"
pydantic = ">=1.8.2, <2.0.0"
requests = "^2.32.2"
cryptography = ">=3.0,<43.1"

[tool.poetry.dev-dependencies]
add-trailing-comma = "^2.2.3"
commitizen = "^2.27.1"
docformatter = "1.5.0"
expects = "^0.9.0"
Faker = "^13.12.0"
isort = "^5.10.1"
mamba = "^0.11.2"
wemake-python-styleguide = "^0.18.0"
pyformat = "^0.7"
mypy = "^1.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.commitizen]
name = "cz_conventional_commits"
version = "0.51.1"
tag_format = "v$version"
bump_message = "bump: Semantic Release Bot: Release Version: $new_version ðŸ¤–ðŸš€ [skip ci]"
version_files = [
    "pyproject.toml:version",
]

[tool.black]
skip-string-normalization = true
line-length = 88
