[tool.poetry]
name = "hamcws"
version = "0.2.7"
description = "homeassistant friendly wrapper for J River MCWS"
authors = ["3ll3d00d <mattkhan+hamcws@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "http://github.com/3ll3d00d/hamcws"
repository = "http://github.com/3ll3d00d/hamcws"
include = [
    "LICENSE",
]
packages = [
    { include = "hamcws" }
]

[tool.poetry.dependencies]
python = "^3.12"
# ha-core head is 3.10.10
aiohttp = "^3.9.1"
pytest = "^8.3.3"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-aiohttp = "*"
pytest-cov = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
