[project]
name = "PV_self-consumption_api_client"
version = "0.1.3"
description = "PV_self-consumption API client"
dependencies = [
    "pydantic>=2.9.2",
    "pandas>=2.2.3",
    "numpy>=2.1.1",
    "requests>=2.32.3",
    "matplotlib>=3.9.2",
    "pyyaml>=6.0.2",
]
requires-python = ">=3.12"
readme = "README.md"
authors = [
    { name = "Sebastien Gardoll", email = "sebastien@gardoll.fr" },
    { name = "Olivier Boucher", email = "olivier.boucher@ipsl.fr" },
]

[project.license]
text = "CeCILL v2.1"

[project.scripts]
pvsc = "pv_self_consumption_api.pvsc:main"

[project.urls]
Repository = "https://github.com/OB-IPSL/PV_self_consumption_client"
Documentation = "https://github.com/OB-IPSL/PV_self_consumption_client"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.scripts.pvsc]
call = "pv_self_consumption_api.pvsc:main"
