# -*- coding: utf-8 -*-

[project]
name = "hshmeng"
version = "2024.10.23.2"
authors = [{ name="hshmeng", email="hshmeng@foxmail.com" }]
description = "You hshmeng ZhiZuoDeZhongWenBianChengBao\n入门输入：from hshmeng.help import *\n帮助()"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
