[build-system]
requires = ["flit_core>=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "grscheller.datastructures"
authors = [
    { name = "Geoffrey R. Scheller", email = "geoffrey@scheller.com" },
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Pytest",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
    "Typing :: Typed"
]
dependencies = [
    "grscheller.circular-array >= 3.6.1, < 3.7",
    "grscheller.fp >= 1.0.0, < 1.1"
]
dynamic = ["version", "description"]
keywords = [
    "datastructures", "data structures",
    "fifo", "lifo", "stack", "queue", "SplitEnd"
] 

[project.optional-dependencies]
test = ["pytest >=8.3"]

[project.urls]
Source = "https://github.com/grscheller/datastructures"
Changelog = "https://github.com/grscheller/datastructures/blob/main/CHANGELOG.md"
Documentation = "https://grscheller.github.io/datastructures/"

[tool.flit.sdist]
exclude = ["dist", "docs", ".gitignore", ".mypy_cache"]

[tool.pylsp-mypy]
enabled = true
live-mode = true
strict = true
report_progress = true

[tool.mypy]
enable_incomplete_feature = ["NewGenericSyntax"]

[tool.pytest.ini_options]
testpaths = ["tests"]
consider_namespace_packages = true

[tool.ruff]
target-version = "py313"

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
