[tool.poetry]
name = "jankenschema"
version = "0.1.2"
description = "Reading schema information from SQLite and being able to create coding schemas"
authors = ["Martin Zheng <jszhengyq@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "jankenschema", from = "." }]

[tool.poetry.dependencies]
python = "^3.12"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pytest-snapshot = "^0.9.0"
pytest-cov = "^5.0.0"

[tool.poetry.scripts]
jankenschema = "jankenschema.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
