[project]
name = "pyreflex"
version = "0.0.0.0.14"
authors = [
  { name = "Caewinix", email = "Caewinix@yeah.net" },
]
dependencies = []
description = "A tiny project that contains reflection functions."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/Caewinix/pyreflex"
"Bug Tracker" = "https://github.com/Caewinix/pyreflex/issues"