[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "utility_toolkit"
version = "0.1.9"
description = "A comprehensive toolkit for AWS operations, database handling, and general utilities."
readme = "README.md"
authors = [{ name = "Eslam Hasanen", email = "Eslamspot@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
keywords = ["tools_box", "tools", "utilities", "toolkit"]
dependencies = [
    "beautifulsoup4==4.12.3",
    "boto3==1.35.27",
    "botocore==1.35.27",
    "chardet==5.2.0",
    "cryptography==43.0.3",
    "lxml==5.3.0",
    "pandas==2.2.3",
    "pdfkit==1.0.0",
    "Pillow==11.0.0",
    "psutil==6.0.0",
    "psycopg2==2.9.9",
    "pytest==8.3.3",
    "python-dotenv==1.0.1",
    "python_magic==0.4.27",
    "reportlab==4.2.2",
    "Requests==2.32.3",
    "SQLAlchemy==2.0.35",
]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://www.idealisticsolutions.com"
"Bug Tracker" = "https://github.com/eslamspot/utility_toolkit/issues"

[project.optional-dependencies]
dev = ["pytest", "black", "flake8", "toolkit", "tools_box", "tools", "utilities"]

[tool.setuptools.packages.find]
where = ["src"]