[tool.poetry]
name = "python-design-patterns"
version = "0.1.1a2"
description = "A Python library for implementing design patterns"
authors = ["Vodkas <vodkas3630@gmail.com>"]
readme = "README_PYPI.md"
license = "MIT"
packages = [
    { include = "pdp" }
]

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
flake8 = "^7.1.1"
pylint = "^3.3.1"
black = "^24.10.0"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
test = "tests.script:run_tests"
test-cov = "tests.script:run_tests_with_cov"