[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dice_calc"
version = "0.3.0.dev0"
description = "Advanced Calculator for Dice"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Ar-Kareem" }
]
maintainers = [
    { name = "Ar-Kareem" }
]
keywords = ["dice", "calculator", "probability", "statistics", "math", "dice-notation", "dice-roller", "dice-roller-simulator", "dice-notation-parser", "dice-notation-compiler", "dice-notation-interpreter", "dice-notation-evaluator", "dice-notation-calculator", "dice-notation-solver", "dice-notation-simulator", "dice-notation-optimizer", "anydice", "anydice-compiler", "anydice-interpreter", "anydice-evaluator", "anydice-calculator", "anydice-solver", "anydice-simulator", "python-dice"]
classifiers = [
    "Development Status :: 4 - Beta",
    
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",

    "License :: OSI Approved :: MIT License",
    
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

requires-python = ">=3.9.0"

[project.urls]
Homepage = "https://github.com/Ar-Kareem/PythonDice/"
Repository = "https://github.com/Ar-Kareem/PythonDice/"
Issues = "https://github.com/Ar-Kareem/PythonDice/issues"

[tool.setuptools]
package-dir = {"dice_calc" = "src", "dice_calc.parser" = "src/parser", "dice_calc.parser.ply" = "src/parser/ply"}

packages = [
    "dice_calc",
    "dice_calc.parser",
    "dice_calc.parser.ply"
]

#build and pypi push            rm dist/* && python -m build --sdist --wheel && python -m twine upload --repository pypi dist/*

# test package locally                 pip uninstall -y dice_calc ; pip install ..\..\..\pythondice\dist\dice_calc-0.0.9.tar.gz ; python ./test.py
