[build-system]
requires = ["setuptools>=42", "wheel"] 
build-backend = "setuptools.build_meta"  

[project]
name = "kerttula"
version = "0.0.1"
description = "Juha's home"
readme = {file = "docs/source/README.rst", content-type = "text/markdown"}
requires-python = ">=3.8"
license = {file = "docs/source/LICENSE.rst", content-type = "text/markdown"}
keywords = ["home", "automation", "juham", "masterpiece"]
authors = [
  {name = "J Meskanen", email = "juham.api@gmail.com" }
]
maintainers = [
  {name = "J. Meskanen", email = "juham.api@gmail.com" }
]

classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "Topic :: Software Development",
  "License :: Public Domain",
  "Programming Language :: Python :: 3.8",
]

dependencies = [
  "juham >= 0.0.4",
  "juham_visualcrossing >= 0.0.1",
  "juham_priceforecast >= 0.0.1",
  "juham_openweathermap >= 0.0.1",
  "pytz >= 2024.1",
  "importlib-metadata"
]

# Add kerttula to path so that kerttula.service can find and start it
[project.scripts]
kerttula = "kerttula.kerttula:main"

[project.optional-dependencies]
dev = ["check-manifest"]

[project.entry-points."kerttula.plugins"]
# none, yet

[project.urls]
"Homepage" = "https://meskanen.com"
"Bug Reports" = "https://meskanen.com"
"Funding" = "https://meskanen.com"
"Say Thanks!" = "http://meskanen.com"
"Source" = "https://meskanen.com"

# Add service file installation
[tool.setuptools.data-files]
# This installs the kerttula.service to /etc/systemd/system
"/etc/systemd/system" = ["kerttula.service"]

[tool.mypy]
files = ["kerttula/*.py", "tests/*.py"]
ignore_missing_imports = true
