name: Release

on:
  push:
    # run only against version tags
    tags:
      - 'v*'

jobs:
  release:
    name: Generate New Release - ${{ github.ref_name }}
    runs-on: ubuntu-latest
    environment: release

    permissions:
      attestations: write
      contents: write  # needed to create GH Release
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing to PyPI
      packages: write  # required for pushing image to GHCR
    
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
        with:
          fetch-depth: 0

      - name: Setup python for build
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
        with:
          python-version: "3.x"

      # run tests
      - name: Install tox
        run: python -m pip install tox-gh>=1.2

      - name: Setup test suite
        run: tox -vv --notest -e test

      - name: Run test suite
        run: tox --skip-pkg-install -e test
      
      # build and publish
      - name: Install Hatch
        run: pipx install hatch

      - name: Build dist artifacts
        run: hatch build
      
      # PyPI Release
      # required instead of using hatch due to usage of trusted publishers
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@897895f1e160c830e369f9779632ebc134688e1b  # v1.10.2
        with:
          repository-url: https://test.pypi.org/legacy/
          print-hash: true
          verbose: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@897895f1e160c830e369f9779632ebc134688e1b  # v1.10.2
        with:
          attestations: true
      
      # Github Release
      - name: Create Github Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191  # v2.0.8
        with:
          name: 
          files: |
            dist/*
          fail_on_unmatched_files: true
          generate_release_notes: true
          make_latest: true
      
      # Docker Release
      # REF: https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages
      - name: Log in to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  # v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Log in to Github Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81  # v5.5.1
        with:
          images: |
            magneticstain/${{ github.repository }}
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker images to all registries
        id: push
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75  # v6.9.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Generate artifact attestation for GHCR
      #   uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c  # v1.4.3
      #   with:
      #     subject-name: ghcr.io/${{ github.repository }}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
      