[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ersst5tools"
version = "0.0.2"
description = "Tools for processing ERSSTv5 data"
authors = [
           { name = "Mutahar Chalmers", email = "mutahar.chalmers@gmail.com" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]
requires-python = ">=3.8"
dependencies = [ "numpy>=1.18", "scipy>=1.10", "xarray>=2023.01.0",
                 "zarr>=2.18", "climperiods>=0.0.2"
]

[project.urls]
"Homepage" = "https://github.com/MutaharChalmers/ersst5tools"
