[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aerialog"
version = "0.0.1"
authors = [
  { name="tomos", email="oerushia@gmail.com" },
]

description = "A simple logger for python, but with colours!"
readme = "README.md"
requires-python = ">=3.8"

classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "python-dotenv",
]

[project.urls]
Homepage = "https://github.com/devtomos/aerialog"
Issues = "https://github.com/devtomos/aerialog/issues"