[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/wam_api"]

[project]
name = "swpc-wamipe"
version = "0.0.1"
authors = [
    { name = "Atheesh Thirumalairajan" },
    { name = "Nand Vinchhi" },
    { name = "Samai Patel" },
    { name = "Gili Gordiyenko" },
    { name = "Anusha Iyer" },
    { name = "Varun Kota" },
    { name = "Arav Luthra" },
    { name = "Scott Chen" }
]

description = "Provides simple APIs to calculate neutral density values using the NOAA Whole Atmosphere Model-Ionosphere Plasmasphere Electrodynamics (WAM-IPE) model"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
]

[project.urls]
"NOAA SWCC Website" = "https://www.swpc.noaa.gov/"
"NOAA WAM-IPE Model" = "https://www.swpc.noaa.gov/products/wam-ipe"
"App Dev Club LLC" = "https://appdevclub.com"