[tool.poetry]
name = "nonebot_plugin_bf5_grouptools"
version = "2.0.2"
description = "基于 Nonebot2 的战地 5 QQ 群管理插件。"
license = "GPL3"
authors = ["Lonely-Sails"]
readme = "README.md"
homepage = "https://github.com/Lonely-Sails/nonebot-plugin-BF5-grouptools"
repository = "https://github.com/Lonely-Sails/nonebot-plugin-BF5-grouptools"
documentation = "https://github.com/Lonely-Sails/nonebot-plugin-BF5-grouptools#readme"
keywords = ["nonebot", "nonebot2", "BF5", "onebot"]

[tool.poetry.dependencies]
httpx = "^0.27.0"
python = "^3.8"
nonebot2 = "^2.2.0"
nonebot-adapter-onebot = "^2.4.3"
nonebot-plugin-localstore = "^0.7.0"

