[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "OpenGL-glut"
authors = [
    {name = "Ruud van der Ham", email = "rt.van.der.ham@gmail.com"}
]
description = "OpenGL with glut support"
version = "3.1.7-0"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3 :: Only"
]
[project.urls]
Homepage = "https://github.com/salabim/opengl"
Repository = "https://github.com/salabim/opengl"


[tool.setuptools.package-data]
"*" = ["*.*"]

