[tool.poetry]
name = "vatman"
version = "0.0.2"
description = "A small utility for drawing image boards"
authors = ["Vadim Fedorov <vadim.ai.lab@gmail.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.10"
pillow = "^10.4.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.5.0"
jupyterlab = "^4.2.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
