[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "photonx"
version = "0.0.2"
authors = [
  { name="Luis El Srouji", email="lzelsrouji@ucdavis.edu" },
]
description = "Collection of scripts useful for photonic design."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/NeuroSumbaD/photonx"