
[build-system]
requires = ["setuptools>=61.0", "versioningit"]
build-backend = "setuptools.build_meta"


# ----------------------------------------- setuptools -------------------------------------------
[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true


# ----------------------------------------- Project Metadata -------------------------------------
#
[project]
version = "0.0.0.dev338"
name = "ControlMan"
dependencies = [
    "packaging >= 23.2, < 24",
    "trove-classifiers >= 2024.9.12",
    "jsonschema >= 4.23, < 5",
    "referencing == 0.35.1",
    "jsonpath-ng == 1.6.1",
    "ruamel.yaml == 0.17.40",
    "PyLinks == 0.0.0.dev40",
    "LoggerMan == 0.0.0.dev56",
    "PySerials == 0.0.0.dev30",
    "GitTidy == 0.0.0.dev53",
    "PkgData == 0.0.0.dev5",
    "PyShellMan == 0.0.0.dev17",
    "PySyntax == 0.0.0.dev3",
    "ExceptionMan == 0.0.0.dev27",
    "MDit == 0.0.0.dev27",
    "JSONSchemata == 0.0.0.dev26",
    "VersionMan == 0.0.0.dev248",
    "HTMP == 0.0.0.dev5",
    "LicenseMan == 0.0.0.dev13",
]
requires-python = ">=3.10"
