[tool.poetry]
name = "mkdocs-juvix-plugin"
version = "0.3.11"
description = "Support for Juvix Markdown files in MkDocs"
authors = ["Jonathan Prieto-Cubides, and GitHub contributors"]
license = "MIT"
readme = "README.md"

classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Programming Language :: Python",
]

packages = [
    { include = "mkdocs_juvix", from = "." },
    { include = "src", from = "." },
]

[tool.poetry.scripts]
juvix-mkdocs = "src.cli:cli"

[tool.poetry.plugins."mkdocs.plugins"]
juvix = "mkdocs_juvix.juvix_markdown:JuvixPlugin"
# extra plugins
todos = "mkdocs_juvix.todos:TodosPlugin"
wikilinks = "mkdocs_juvix.links:WikilinksPlugin"
images = "mkdocs_juvix.images:ImagesPlugin"
# differ = "mkdocs_juvix.differ:DifferPlugin"

[tool.poetry.dependencies]
python = ">=3.10,<4"
mkdocs = "^1.6.1"
click = "^8.1.7"
semver = "^3.0.2"
mkdocs-material = "^9.5.40"
questionary = "^2.0.1"
python-dotenv = "^1.0.1"
bs4 = "^0.0.2"
toml = "^0.10.2"
pymdown-extensions = "^10.11.2"
fuzzywuzzy = "^0.18.0"
graphviz = "^0.20.3"
python-levenshtein = "^0.26.0"
intervaltree = "^3.1.0"
ncls = "^0.0.68"
trio = "^0.27.0"
tqdm = "^4.66.5"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.9"
pre-commit = "^4.0.1"
twine = "^5.1.1"
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"




[tool.poetry.group.test.dependencies]
pytest = "*"

[tool.pytest.ini_options]
testpaths = ["test"]
addopts = "-v --tb=short"
